export const editorTheme = {
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder: 'text-muted-foreground',
  paragraph: 'mb-2 leading-7',
  quote: 'border-l-4 border-border pl-4 italic text-muted-foreground bg-muted/50 rounded-r-md py-2 my-4',
  heading: {
    h1: 'text-4xl font-bold mb-4 mt-6 text-foreground',
    h2: 'text-3xl font-bold mb-3 mt-5 text-foreground',
    h3: 'text-2xl font-bold mb-3 mt-4 text-foreground',
    h4: 'text-xl font-bold mb-2 mt-3 text-foreground',
    h5: 'text-lg font-bold mb-2 mt-3 text-foreground',
    h6: 'text-base font-bold mb-2 mt-3 text-foreground',
  },
  list: {
    nested: {
      listitem: 'list-none',
    },
    ol: 'list-decimal list-inside space-y-1 ml-4',
    ul: 'list-disc list-inside space-y-1 ml-4',
    listitem: 'mb-1',
    listitemChecked: 'relative pl-6 line-through opacity-60',
    listitemUnchecked: 'relative pl-6',
  },
  hashtag: 'text-blue-500 hover:text-blue-600',
  image: 'inline-block max-w-full h-auto rounded-md',
  link: 'text-primary underline hover:text-primary/80 cursor-pointer',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    overflowed: '...',
    hashtag: 'text-blue-500',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-muted px-1.5 py-0.5 rounded text-sm font-mono text-foreground',
    subscript: 'text-xs align-sub',
    superscript: 'text-xs align-super',
  },
  code: 'bg-muted border border-border rounded-md p-4 font-mono text-sm whitespace-pre-wrap overflow-x-auto',
  codeHighlight: {
    atrule: 'text-purple-600',
    attr: 'text-blue-600',
    boolean: 'text-orange-600',
    builtin: 'text-purple-600',
    cdata: 'text-gray-600',
    char: 'text-green-600',
    class: 'text-blue-600',
    'class-name': 'text-blue-600',
    comment: 'text-gray-500 italic',
    constant: 'text-orange-600',
    deleted: 'text-red-600',
    doctype: 'text-gray-600',
    entity: 'text-orange-600',
    function: 'text-blue-600',
    important: 'text-red-600 font-bold',
    inserted: 'text-green-600',
    keyword: 'text-purple-600',
    namespace: 'text-purple-600',
    number: 'text-orange-600',
    operator: 'text-gray-700',
    prolog: 'text-gray-600',
    property: 'text-blue-600',
    punctuation: 'text-gray-700',
    regex: 'text-green-600',
    selector: 'text-blue-600',
    string: 'text-green-600',
    symbol: 'text-orange-600',
    tag: 'text-red-600',
    url: 'text-blue-600 underline',
    variable: 'text-orange-600',
  },
  table: 'border-collapse border border-border w-full my-4',
  tableCell: 'border border-border p-2 min-w-16',
  tableCellHeader: 'border border-border p-2 bg-muted font-semibold',
  tableRow: 'border-b border-border',
  tableSelection: 'bg-blue-100',
};